export const ErrorCodes = {
  // Generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',

  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_INACTIVE_ACCOUNT: 'AUTH_INACTIVE_ACCOUNT',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_REUSE_DETECTED: 'AUTH_TOKEN_REUSE_DETECTED',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_REFRESH_REQUIRED: 'AUTH_REFRESH_REQUIRED',
  AUTH_RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',
  AUTH_RESET_TOKEN_EXPIRED: 'AUTH_RESET_TOKEN_EXPIRED',
  AUTH_PASSWORD_MISMATCH: 'AUTH_PASSWORD_MISMATCH',
  AUTH_PASSWORD_WEAK: 'AUTH_PASSWORD_WEAK',
  AUTH_PASSWORD_REUSED: 'AUTH_PASSWORD_REUSED',
  AUTH_2FA_REQUIRED: 'AUTH_2FA_REQUIRED',

  // Admins / roles
  ADMIN_EXISTS: 'ADMIN_EXISTS',
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
  ADMIN_INVITE_INVALID: 'ADMIN_INVITE_INVALID',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_SYSTEM_PROTECTED: 'ROLE_SYSTEM_PROTECTED',
  ROLE_IN_USE: 'ROLE_IN_USE',

  // Products
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_VALIDATION_FAILED: 'PRODUCT_VALIDATION_FAILED',
  PRODUCT_SLUG_EXISTS: 'PRODUCT_SLUG_EXISTS',
  PRODUCT_SKU_EXISTS: 'PRODUCT_SKU_EXISTS',
  PRODUCT_VERSION_CONFLICT: 'PRODUCT_VERSION_CONFLICT',
  PRODUCT_ALREADY_PUBLISHED: 'PRODUCT_ALREADY_PUBLISHED',
  PRODUCT_NOT_PUBLISHED: 'PRODUCT_NOT_PUBLISHED',
  UNKNOWN_FILTER_KEY: 'UNKNOWN_FILTER_KEY',
  INVALID_ATTRIBUTE: 'INVALID_ATTRIBUTE',
  UNSUPPORTED_SORT_FIELD: 'UNSUPPORTED_SORT_FIELD',
  PAGE_SIZE_EXCEEDED: 'PAGE_SIZE_EXCEEDED',
  INVALID_CURSOR: 'INVALID_CURSOR',

  // Categories / filters
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_SLUG_EXISTS: 'CATEGORY_SLUG_EXISTS',
  CATEGORY_HAS_CHILDREN: 'CATEGORY_HAS_CHILDREN',
  FILTER_NOT_FOUND: 'FILTER_NOT_FOUND',
  FILTER_KEY_EXISTS: 'FILTER_KEY_EXISTS',
  FILTER_IN_USE: 'FILTER_IN_USE',

  // Media / R2
  MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
  MEDIA_UPLOAD_INVALID: 'MEDIA_UPLOAD_INVALID',
  MEDIA_TYPE_NOT_ALLOWED: 'MEDIA_TYPE_NOT_ALLOWED',
  MEDIA_TOO_LARGE: 'MEDIA_TOO_LARGE',
  MEDIA_STORAGE_ERROR: 'MEDIA_STORAGE_ERROR',
  MEDIA_PROCESSING_FAILED: 'MEDIA_PROCESSING_FAILED',

  // Bulk import
  IMPORT_NOT_FOUND: 'IMPORT_NOT_FOUND',
  IMPORT_INVALID_FILE: 'IMPORT_INVALID_FILE',
  IMPORT_TOO_LARGE: 'IMPORT_TOO_LARGE',
  IMPORT_TOO_MANY_ROWS: 'IMPORT_TOO_MANY_ROWS',
  IMPORT_CANNOT_CANCEL: 'IMPORT_CANNOT_CANCEL',
  IMPORT_CANNOT_RETRY: 'IMPORT_CANNOT_RETRY',
  IMPORT_DUPLICATE: 'IMPORT_DUPLICATE',
  IMPORT_ZIP_VIOLATION: 'IMPORT_ZIP_VIOLATION',

  // Customer requests
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  REQUEST_STATUS_INVALID: 'REQUEST_STATUS_INVALID',
  REQUEST_DUPLICATE: 'REQUEST_DUPLICATE',

  // Audit
  AUDIT_QUERY_INVALID: 'AUDIT_QUERY_INVALID',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
